### ISSUE TITLE
Separate images for ubuntu/debian releases

### ISSUE THREAD

**Issue by Shm013** [pycontribs/pys#15]
Can you make separate ubuntu-xenial, ubuntu-bionic, ubuntu-focal and debian-* images as well as centos?

**Comment by ayr-ton** [comment]
@ssbarnea Is this still being maintened?

**Comment by ssbarnea** [comment]
This project is not under active maintenance but I will likely accept new PRs on it. I am aware of several project using these images for testing, mostly those using molecule-podman and molecule-docker drivers.

Still considering that PSF has official container images based on debian, I see no reason to add them here: https://hub.docker.com/_/python

PS. But because there are no official images for centos with python, adding these would be welcomed.

**Comment by ayr-ton** [comment]
@ssbarnea will send some PRs then. \o/
